/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Vinicius Dierings
 */
public class GradesAverageCalculator extends javax.swing.JFrame {

    //Object
    GradesCalculator gradesCalculator = new GradesCalculator();

    DefaultListModel listFaceW = new DefaultListModel();
    DefaultListModel listFaceG = new DefaultListModel();
    DefaultListModel listResult = new DefaultListModel();
    double total = 0;
    int currentGradesAdded = 0;// Control the number of items added an the fow of the array

    /**
     * Creates new form interfaceProgram
     */
    public GradesAverageCalculator() {
        initComponents();
        btnRemove.setEnabled(false);
        btnCalc.setEnabled(false);
        btnAdd.setEnabled(false);
        setResizable(false);
        txtError.hide();
        JOptionPane.showMessageDialog(rootPane, "Welcome! This program is to help you to calculate your final average of a subjet or make simulations of grades that you need to get.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gradeResult = new javax.swing.JLabel();
        textInfo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnQuantaty = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGrades = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        spnNum = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstWeight = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        txtValueW = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValueG = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtError = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstResult = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRADE AVERAGE CALCULATOR");

        jLabel2.setText("Developed by Douglas V. Dierings");

        gradeResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gradeResult.setForeground(new java.awt.Color(0, 102, 0));
        gradeResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradeResult.setText("RESULT");

        textInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textInfo.setText("Enter the quantaty of grades you have for the subjet:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("FINAL AVERAGE:");

        btnQuantaty.setText("CONFIRM");
        btnQuantaty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantatyActionPerformed(evt);
            }
        });

        lstGrades.setModel(listFaceG);
        lstGrades.setToolTipText("");
        lstGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstGradesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstGrades);

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnRemove.setText("CLEAR FIELDS");
        btnRemove.setMaximumSize(new java.awt.Dimension(95, 22));
        btnRemove.setMinimumSize(new java.awt.Dimension(95, 22));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        spnNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        spnNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spnNumKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter in the fields below the weight and the grade you got, then click on add:");

        lstWeight.setModel(listFaceW);
        lstWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstWeightMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstWeight);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WEIGHTS");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GRADES");

        btnCalc.setText("CALCULATE");
        btnCalc.setMaximumSize(new java.awt.Dimension(95, 22));
        btnCalc.setMinimumSize(new java.awt.Dimension(95, 22));
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        txtValueW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueWActionPerformed(evt);
            }
        });

        jLabel7.setText("%");

        txtValueG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueGActionPerformed(evt);
            }
        });

        jLabel8.setText("%");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("WEIGHT");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GRADE");

        txtError.setForeground(new java.awt.Color(255, 0, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("\"error message\"");

        lstResult.setBackground(new java.awt.Color(153, 255, 255));
        lstResult.setModel(listResult);
        jScrollPane3.setViewportView(lstResult);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AVERAGE");

        jLabel12.setText("Version 1.2.2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textInfo)
                                .addGap(12, 12, 12)
                                .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnQuantaty))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gradeResult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtValueW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE))
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtValueG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel8)
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(txtError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInfo)
                    .addComponent(spnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuantaty))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtValueW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtValueG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addComponent(btnAdd))
                                .addGap(5, 5, 5)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(gradeResult)
                                    .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            txtError.hide();
            if (Double.parseDouble(txtValueW.getText()) > 100 || Double.parseDouble(txtValueG.getText()) > 100) {
                txtError.setText("The weight and grades can not be bigger then 100!");
                txtError.show();
                return;
            }
            gradesCalculator.addGrade(Double.parseDouble(txtValueW.getText()), Double.parseDouble(txtValueG.getText()));
            listFaceW.setElementAt(txtValueW.getText(), currentGradesAdded);
            listFaceG.setElementAt(txtValueG.getText(), currentGradesAdded);
            currentGradesAdded++;
        } catch (NumberFormatException e) {
            txtError.setText("Do not enter letters or leave any fields empty!");
            txtError.show();
        }
        if (currentGradesAdded == gradesCalculator.getGradesQuantity()) {
            btnAdd.setEnabled(false);
            btnCalc.setEnabled(true);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void lstWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstWeightMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstWeightMouseClicked

    private void lstGradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGradesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstGradesMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        listFaceW.clear();
        listFaceG.clear();
        listResult.clear();
        txtValueW.setText(null);
        txtValueG.setText(null);
        gradesCalculator.cleanLists();
        gradeResult.setText("RESULT");
        for (int o = 0; o < gradesCalculator.getGradesQuantity(); o++) {
            listFaceW.addElement(0);
            listFaceG.addElement(0);
        }
        btnAdd.setEnabled(true);
        gradesCalculator.setTotal(0);
        gradesCalculator.setGradesQuantity(0);
        currentGradesAdded = 0;
        btnCalc.setEnabled(false);
        txtError.hide();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnQuantatyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantatyActionPerformed
        // TODO add your handling code here:
        gradesCalculator.addGradesQuantity(Integer.parseInt(spnNum.getValue().toString()));
        listFaceW.removeAllElements();
        listFaceG.removeAllElements();
        listResult.removeAllElements();
        for (int g = 0; g < gradesCalculator.getGradesQuantity(); g++) {
            listFaceW.addElement(0);
            listFaceG.addElement(0);
        }
        gradesCalculator.setTotal(0);
        listResult.clear();
        currentGradesAdded = 0;
        btnAdd.setEnabled(true);
        btnRemove.setEnabled(true);
        gradeResult.setText("RESULT");
        txtValueW.setText(null);
        txtValueG.setText(null);
        txtError.hide();
    }//GEN-LAST:event_btnQuantatyActionPerformed

    private void txtValueWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueWActionPerformed

    private void txtValueGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueGActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        gradesCalculator.calculateAverage();
        gradeResult.setText(String.format("%.2f", gradesCalculator.averageTotal()) + "%");
        for (int w = 0; w < currentGradesAdded; w++) {
            listResult.addElement(gradesCalculator.calculateAverage().get(w) + "%");
        }
        gradesCalculator.cleanLists();
        total = 0;
        btnCalc.setEnabled(false);
        txtError.hide();
    }//GEN-LAST:event_btnCalcActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void spnNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_spnNumKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesAverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesAverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesAverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesAverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesAverageCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnQuantaty;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel gradeResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstGrades;
    private javax.swing.JList<String> lstResult;
    private javax.swing.JList<String> lstWeight;
    private javax.swing.JSpinner spnNum;
    private javax.swing.JLabel textInfo;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtValueG;
    private javax.swing.JTextField txtValueW;
    // End of variables declaration//GEN-END:variables
}
